using System;

namespace Xunit.Fixture.Api.Extensions
{
    /// <summary>
    /// Extensions for <see cref="IApiTestFixture"/>.
    /// </summary>
    public static class PropertyExtensions
    {
        /// <summary>
        /// Adds the specified property value to the specified key.
        /// </summary>
        /// <param name="fixture">The fixture.</param>
        /// <param name="key">The key.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        public static IApiTestFixture HavingProperty(this IApiTestFixture fixture, string key, object value)
        {
            fixture.Properties[key] = value;
            return fixture;
        }

        /// <summary>
        /// Adds the property value generated by the specified factory to the specified key.
        /// </summary>
        /// <param name="fixture">The fixture.</param>
        /// <param name="key">The key.</param>
        /// <param name="valueFactory">The value factory.</param>
        /// <returns></returns>
        public static IApiTestFixture HavingProperty(this IApiTestFixture fixture, string key, Func<object> valueFactory) =>
            fixture.HavingProperty(key, valueFactory());

        /// <summary>
        /// Runs the specified fixture action if a property exists in the fixture that matches the specified value predicate.
        /// </summary>
        /// <param name="fixture">The fixture.</param>
        /// <param name="key">The key.</param>
        /// <param name="valuePredicate">The value predicate.</param>
        /// <param name="action">The action.</param>
        /// <returns></returns>
        public static IApiTestFixture OnlyWhenHavingStringProperty(this IApiTestFixture fixture,
                                                               string key,
                                                               Func<string, bool> valuePredicate,
                                                               Action<IApiTestFixture> action)
        {
            if (fixture.Properties.TryGetValue(key, out var value) && value is string s && valuePredicate(s))
            {
                action(fixture);
            }

            return fixture;
        }

        /// <summary>
        /// Runs the specified fixture action if a property exists in the fixture that matches the specified value.
        /// </summary>
        /// <param name="fixture">The fixture.</param>
        /// <param name="key">The key.</param>
        /// <param name="value">The value.</param>
        /// <param name="action">The action.</param>
        /// <returns></returns>
        public static IApiTestFixture OnlyWhenHavingStringProperty(this IApiTestFixture fixture,
                                                               string key,
                                                               string value,
                                                               Action<IApiTestFixture> action) =>
            fixture.OnlyWhenHavingStringProperty(key, x => x == value, action);

        /// <summary>
        /// Gets the property of the specified type with the specified key.
        /// </summary>
        /// <typeparam name="TProperty">The type of the property.</typeparam>
        /// <param name="fixture">The fixture.</param>
        /// <param name="key">The key.</param>
        /// <returns></returns>
        public static TProperty GetProperty<TProperty>(this IApiTestFixture fixture, string key)
        {
            if (!fixture.Properties.ContainsKey(key))
            {
                throw new ArgumentException("Cannot find test fixture property with key: " + key);
            }

            if (fixture.Properties[key] is TProperty p)
            {
                return p;
            }

            throw new ArgumentException($"Test fixture property with key: {key} is not a {typeof(TProperty)}");
        }
    }
}
